language: ruby
rvm:
- 2.2.10
- 2.3.8
- 2.4.6
- 2.6.2
before_install: gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false
