language: ruby
rvm:
- 2.2.10
- 2.3.8
- 2.4.9
- 2.5.7
- 2.6.5
- 2.7.0-preview2
before_install: gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    - djberg96@gmail.com
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - rvm: 2.2.10
    - rvm: 2.3.8
